### ISSUE TITLE
可以给个插件功能吗

### ISSUE THREAD

**Issue by padoruuu** [y3-editor/y3-helper#10]
汐佬可以像w2l一样搞个插件功能吗，比如y3助手监听到编辑器保存时调用一下lua的插件，有些东西想自己去读取处理移交方便些，比如我想做图标名跟资源ID的映射，比如矩形区域名跟矩形ID的映射之类的，物编单位名和单位ID等。。

**Comment by sumneko** [comment]
加了，不过是js的
