### ISSUE TITLE
插件与lua的交互? 

### ISSUE THREAD

**Issue by xuhuanzy** [y3-editor/y3-helper#12]
插件的读表工具很难处理复杂表, 而一般来说表会导出成`lua`, 建议插件能够读lua表.
比如说有个表管理配置工具[`luban`,](https://github.com/focus-creative-games/luban), 支持非常复杂的表导出到`lua`

**Comment by xuhuanzy** [comment]
> 到底是要导出到Lua还是读取Lua然后导到物编里

插件读取lua, 然后导出到物编

**Comment by sumneko** [comment]
Lua是静态数据表，还是里面会有表达式甚至语句？内容形式是 `return { .. }` 吗？

**Comment by xuhuanzy** [comment]
从lua导出一份json表给插件系统也行

**Comment by sumneko** [comment]
> 从lua导出一份json表给插件系统也行, 就是可能在js那边还要再做处理

我的意思是表管理系统直接导出成json，由插件负责导成Lua

**Comment by xuhuanzy** [comment]
luban的导出是带你自己标注的类型信息的，可以一次性生成lua表+lua表的类型注解，使用lua二次处理很方便。
使用ts处理的话，为了ide提示可能要再额外给ts标注一份类型信息？感觉来回处理挺麻烦的。
