### ISSUE TITLE
bug: 命令 - 生成物编模板（CSV）

### ISSUE THREAD

**Issue by ChouUn** [y3-editor/y3-helper#16]
```log
模板生成异常:Error: ENOENT: no such file or directory, rename 
'c:\Users\Administrator\.vscode\extensions\template\csv\unit' -> 
'c:\Users\Administrator\.vscode\extensions\template\csv\单位'
```
该命令由以下代码注册
https://github.com/y3-editor/y3-helper/blob/6f2a56160f0fac679695fa12bba25152e527e035/src/editorTable/CSV/index.ts#L246-L259
其所调用到的诸如此类的代码
https://github.com/y3-editor/y3-helper/blob/6f2a56160f0fac679695fa12bba25152e527e035/src/editorTable/CSV/templateGenerator.ts#L54-L55
打包后，插件目录结构是
```plain
.
└── extensions/
    └── sumneko.y3-helper-1.11.1/
        └── dist/
            └── extension.js
```
`extensions\sumneko.y3-helper-1.11.1\dist\` + `../../template/csv` => `extensions\template\csv\`
是不是这里导致路径拼接出问题  

version: 1.11.1
ps: y3-helper.generateExcelTemplate 虽被列出，但未被注册。

**Comment by sumneko** [comment]
你的需求是啥，可以改用插件实现吗

**Comment by ChouUn** [comment]
> 你的需求是啥，可以改用插件实现吗

我的需求是调研修改物编的方案们。
所以我根据源码把可能的方案都过一遍。

也调研过插件，我在尝试读一个具体的 excel（.xls）时失败了。
`y3.excel.loadFile` 能读取到 Workbook 一级，但是继续读取 Worksheet 时无法识别。
https://github.com/y3-editor/y3-helper/blob/6f2a56160f0fac679695fa12bba25152e527e035/src/editorTable/excel/index.ts#L22-L25

所以我准备手动调用 `exceljs` 进行调试，然后发现目前没法正常 require 本地文件和第三方库。
比如执行 `require('./test')` 和 `require('exceljs')`，都会导致 extension.js 内容被全文输出一遍（作为报错的上下文），并获得一个 `Error: Cannot find module 'xxx'`。
相关代码应该是同一处，`??` 的后面。
https://github.com/y3-editor/y3-helper/blob/6f2a56160f0fac679695fa12bba25152e527e035/src/plugin/plugin.ts#L217

没仔细研究过 `vm` 这个 module，暂时没有解决这个问题的头猪。

**Comment by sumneko** [comment]
sheetName 尽量传字符串。因为如果删除、移动过sheet的话，第一个sheet的索引不一定是1

**Comment by sumneko** [comment]
require的问题我研究一下

**Comment by ChouUn** [comment]
> sheetName 尽量传字符串

我一开始尝试的便是 by name，寄了。
所以换成 1，仍然寄了。
留空 undefined，走了 1 的逻辑应该，仍然寄了。

↑ 这是我之前进行过的尝试

> 因为如果删除、移动过sheet的话，第一个sheet的索引不一定是1

got. 之后我枚举下后面的 index 试试

**Comment by sumneko** [comment]
1.11.2 版本支持 require 了
