### ISSUE TITLE
切换场景导致当前场景 meta 丢失

### ISSUE THREAD

**Issue by ldoubil** [y3-editor/y3-helper#18]
https://github.com/y3-editor/y3-helper/blob/9da20d30cc923528b5886e8c9bc44800338f75d9/src/extension.ts#L40-L44
https://github.com/y3-editor/y3-helper/blob/9da20d30cc923528b5886e8c9bc44800338f75d9/src/extension.ts#L42
切换场景导致当前场景 meta 丢失 或许是因为这行，还没有获取到新场景的目录然后就清空了。

**Comment by sumneko** [comment]
今天看一下
