### ISSUE TITLE
插件修改unit物编挂载技能bug

### ISSUE THREAD

**Issue by jakiol** [y3-editor/y3-helper#25]
在1.18.0的版本js插件刷物编修改技能正常
![image](https://github.com/user-attachments/assets/a6629d6b-4a70-4bd6-b39e-c36cae691486)
在这个之后的版本物编修改技能会默认把数值改为小数
![image](https://github.com/user-attachments/assets/6cae1515-04bd-4eb4-92fc-fb45142911ad)
如果用编辑器打开的话会产生问题

**Comment by sumneko** [comment]
1.18.9 改回去了
