### ISSUE TITLE
首次初始化有，第二次打开插件里面菜单全没了

### ISSUE THREAD

**Issue by 314599782** [y3-editor/y3-helper#4]
首次初始化有，第二次打开插件里面菜单全没了

**Comment by sumneko** [comment]
在 “输出”（Ctrl+Shift+U）窗口里，切换到 Y3开发助手 和 扩展宿主 里，找一下有没有报错，截图看一下

**Comment by 314599782** [comment]
输出里面是空的


&nbsp;


hewei
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月23日(星期二) 下午3:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [y3-editor/y3-helper] 首次初始化有，第二次打开插件里面菜单全没了 (Issue #4)














 
在 “输出”（Ctrl+Shift+U）窗口里，切换到 Y3开发助手 和 扩展宿主 里，找一下有没有报错，截图看一下

**Comment by 314599782** [comment]
![image](https://github.com/y3-editor/y3-helper/assets/13996502/adc1f715-696e-4d09-83e2-ff8b38686453)

**Comment by sumneko** [comment]
![image](https://github.com/y3-editor/y3-helper/assets/5213431/fe016e98-32bd-4156-b35c-31a1af65e810)

**Comment by 314599782** [comment]
![image](https://github.com/y3-editor/y3-helper/assets/13996502/8ec8eef9-ce6b-405a-a8bb-a707f29c6a3a)
如果开启cliclilua插件就会有这个错误，关闭cliclilua就好了

**Comment by sumneko** [comment]
嗯，那个插件把所有插件都搞跪了

**Comment by 314599782** [comment]
https://163.com/learn/project/d/15?Aid=9
我是在这个教程里看到让我装这个clicliua插件的，其实我都不知道有什么用
