### ISSUE TITLE
启动游戏并添加调试器报错

### ISSUE THREAD

**Issue by yangxy6855** [y3-editor/y3-helper#8]
![Snipaste_2024-05-19_13-34-22](https://github.com/y3-editor/y3-helper/assets/36467748/f3ee9b13-7e9a-4341-b642-a8c73df4c3f6)
![Snipaste_2024-05-19_13-33-23](https://github.com/y3-editor/y3-helper/assets/36467748/5de06af2-178f-4b69-82ac-8bcb178a65dc)

**Comment by sumneko** [comment]
终端改成cmd或powershell试试?

**Comment by yangxy6855** [comment]
终端换成cmd后就可以了，之前默认的终端是 git bash,改成 cmd 就可以了；谢谢大佬~
